groups:
- name: swarm_node.rules.yml
  rules:
  - alert: node_cpu_usage
    expr: 1100 - (avg by(host) (cpu_usage_idle / 100) * 100) > 80
    for: 1m
    labels:
      severity: warning
    annotations:
      description: Swarm node {{ $labels.host }} CPU usage is at {{ humanize $value}}%.
      summary: CPU alert for Swarm node '{{ $labels.host }}'
  - alert: node_memory_usage
    expr: mem_used_percent > 80
    for: 1m
    labels:
      severity: warning
    annotations:
      description: Swarm node {{ $labels.host }} Memory usage is at {{ humanize $value}}%.
      summary: Memory alert for Swarm node '{{ $labels.host }}'
  - alert: node_disk_usage_70_percent
    expr: disk_used_percent > 70
    for: 1m
    labels:
      severity: warning
    annotations:
      description: Swarm node {{ $labels.host }} s {{ $labels.device }} disk usage is at {{ humanize
        $value}}%.
      summary: Disk alert for Swarm node '{{ $labels.host }}' s {{ $labels.device }} 
  - alert: node_disk_fill_rate_12h
    expr: predict_linear(disk_free[1h], 12 * 3600) < 0
    for: 1h
    labels:
      severity: critical
    annotations:
      description: Swarm node {{ $labels.host }} s {{ $labels.device }} disk is going to fill up in
        12h.
      summary: Disk fill alert for Swarm node '{{ $labels.node_name }}' s {{ $labels.device }}