groups:
- name: swarm_components.rules.yml
  rules:
  - alert: node_cpu_usage
    expr: 1100 - (avg by(host) (cpu_usage_idle / 100) * 100) > 80
    for: 1m
    labels:
      severity: warning
    annotations:
      description: Swarm node {{ $labels.host }} CPU usage is at {{ humanize $value}}%.
      summary: CPU alert for Swarm node '{{ $labels.host }}'