groups:
- name: swarm_task.rules.yml
  rules:
  - alert: task_high_cpu_usage_50
    expr: docker_container_cpu_usage_percent > 50
    for: 1m
    annotations:
      description: '{{ $labels.container_name }} ||  on ''{{
        $labels.engine_host }}'' CPU usage is at {{ humanize
        $value}}%.'
      summary: CPU alert for Swarm task '{{ $labels.container_name}}' on '{{ $labels.engine_host }}'
  - alert: task_high_memory_usage_1g
    expr: docker_container_mem_usage_percent > 50
    for: 1m
    annotations:
      description: '{{ $labels.container_name }} ||  on ''{{
        $labels.engine_host }}'' Memory usage is at {{ humanize
        $value}}%.'
      summary: Memory alert for Swarm task '{{ $labels.container_name}}' on '{{ $labels.engine_host }}'
  - alert: desired_vs_running_containers_mismatch
    expr: docker_swarm_tasks_desired / docker_swarm_tasks_desired < 1
    for: 1m
    annotations:
      description: 'Number of Running containers is less than the number of desired containers in service {{ $labels.service_name }} ||  with Service Mode ''{{
        $labels.service_mode }}'' || {{ humanize
        $value}}%.'
      summary: Memory alert for Swarm service '{{ $labels.service_mode}}' mismatch
  - alert: oomkilled_task
    expr: min_over_time(docker_container_status_oomkilled[10m]) != 0
    for: 0m
    annotations:
      description: 'Container OOMKilled {{ $labels.container_name }} ||  on ''{{
        $labels.engine_host }}'' Boolean Value is at {{ humanize
        $value}}%.'
      summary: OOMKilled alert for container '{{ $labels.container_name}}' on '{{ $labels.engine_host }}'
  - alert: docker_container_status_exitcode
    expr: min_over_time(docker_container_status_exitcode[10m]) != 0
    for: 0m
    annotations:
      description: 'Failed exit of container {{ $labels.container_name }} ||  on ''{{
        $labels.engine_host }}'' Boolean Value is at {{ humanize
        $value}}%.'
      summary: Failed exit of container '{{ $labels.container_name}}' on '{{ $labels.engine_host }}'

      